# Generated by Django 4.0.6 on 2023-03-22 14:50

import django.contrib.postgres.fields
from django.db import migrations, models
import ndarraydjango.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MlCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('category_vector', django.contrib.postgres.fields.ArrayField(base_field=ndarraydjango.fields.NDArrayField(editable=True, shape=384), blank=True, size=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
