# Generated by Django 4.0.6 on 2023-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_components', '0002_alter_mlcategory_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
