# Generated by Django 4.0.6 on 2023-05-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_changingsentiment'),
        ('tweet_binder', '0011_tweetbinderpost_imp_sentiment'),
        ('twenty_four_seven', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttwentyfourseven',
            name='project_type',
            field=models.CharField(choices=[('online', 'Online'), ('social', 'Social')], default='Online', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='online_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.post'),
        ),
        migrations.AlterField(
            model_name='item',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tfs_project_items', to='twenty_four_seven.projecttwentyfourseven'),
        ),
        migrations.AlterField(
            model_name='item',
            name='social_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet_binder.tweetbinderpost'),
        ),
    ]
