# Generated by Django 4.0.6 on 2023-05-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twenty_four_seven', '0002_projecttwentyfourseven_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('PCK', 'Picking'), ('SUM', 'Summary'), ('QA', 'Q&A Check'), ('PING', 'Publishing'), ('PED', 'Published'), ('IRR', 'Irrelevant')], default='Picking', max_length=20),
        ),
    ]
