# Generated by Django 4.0.6 on 2023-05-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twenty_four_seven', '0003_item_is_back_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Picking', 'Picking'), ('Summary', 'Summary'), ('Q&A Check', 'Q&A Check'), ('Publishing', 'Publishing'), ('Published', 'Published'), ('Irrelevant', 'Irrelevant')], default='Picking', max_length=20),
        ),
    ]
