# Generated by Django 4.0.6 on 2023-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twenty_four_seven', '0004_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='header',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
