# Generated by Django 4.0.6 on 2023-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twenty_four_seven', '0008_alter_projecttwentyfourseven_author_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='header',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
