# Generated by Django 4.0.6 on 2023-08-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twenty_four_seven', '0009_alter_item_header_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warecipient',
            name='mobile_number',
            field=models.CharField(max_length=50),
        ),
    ]
