# Generated by Django 4.0.6 on 2023-08-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0003_talkwalkerpost_full_text'),
        ('twenty_four_seven', '0010_alter_warecipient_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttwentyfourseven',
            name='expert_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='online_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talkwalker.talkwalkerpost'),
        ),
    ]
