# Generated by Django 4.0.6 on 2023-10-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_post_source_type_alter_changingonlinesentiment_post'),
        ('twenty_four_seven', '0011_projecttwentyfourseven_expert_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.post'),
        ),
    ]
