# Generated by Django 4.0.6 on 2023-11-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twenty_four_seven', '0012_item_post'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='twenty four seven online item uniqueness constraint',
        ),
        migrations.RemoveField(
            model_name='item',
            name='online_post',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('project_id', 'post'), name='twenty four seven online item uniqueness constraint'),
        ),
    ]
