# Generated by Django 4.0.6 on 2023-12-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twenty_four_seven', '0013_remove_item_twenty four seven online item uniqueness constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='header_ar',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='text_ar',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
