# Generated by Django 4.0.6 on 2023-11-13 12:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_filters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='query',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
