export const action = {
  LOGOUT: 'LOGOUT',
  GET_PROJECTS: 'GET_PROJECTS',
  GET_WORKSPACES: 'GET_WORKSPACES',
  GET_USER_INFORMATION: 'GET_USER_INFORMATION',
  CREATE_PROJECT: 'CREATE_PROJECT',
  CREATE_WORKSPACE: 'CREATE_WORKSPACE',
  UPDATE_NEW_WORKSPACE: 'UPDATE_NEW_WORKSPACE',
  UPDATE_KEYWORDS_LIST: 'UPDATE_KEYWORDS_LIST',
  CLEAR_KEYWORDS_LIST: 'CLEAR_KEYWORDS_LIST',
}

export const mutator = {
  SET_LOADING: 'SET_LOADING',
  SET_PROJECT: 'SET_PROJECT',
  SET_PROJECTS: 'SET_PROJECTS',
  SET_WORKSPACES: 'SET_WORKSPACES',
  SET_USER_INFORMATION: 'GET_USER_INFORMATION',
  SET_NEW_WORKSPACE: 'SET_NEW_WORKSPACE',
  SET_KEYWORDS_LIST: 'SET_KEYWORDS_LIST',
  DELETE_KEYWORDS_LIST: 'DELETE_KEYWORDS_LIST',
}

export const get = {
  LOADING: 'LOADING',
  PROJECT: 'PROJECT',
  PROJECTS: 'PROJECTS',
  WORKSPACES: 'WORKSPACES',
  USER_ID: 'USER_ID',
  NEW_PROJECT: 'NEW_PROJECT',
  KEYWORDS: 'KEYWORDS',
}
