export const action = {
  LOGOUT: 'LOGOUT',
  GET_PROJECTS: 'GET_PROJECTS',
  GET_WORKSPACES: 'GET_WORKSPACES',
  GET_USER_INFORMATION: 'GET_USER_INFORMATION',
  CREATE_PROJECT: 'CREATE_PROJECT',
  CREATE_WORKSPACE: 'CREATE_WORKSPACE',
}

export const mutator = {
  SET_LOADING: 'SET_LOADING',
  SET_PROJECT: 'SET_PROJECT',
  SET_PROJECTS: 'SET_PROJECTS',
  SET_WORKSPACES: 'SET_WORKSPACES',
  SET_USER_INFORMATION: 'GET_USER_INFORMATION',
}

export const get = {
  LOADING: 'LOADING',
  PROJECT: 'PROJECT',
  PROJECTS: 'PROJECTS',
  WORKSPACES: 'WORKSPACES',
  USER_ID: 'USER_ID',
}
