const initialState = {
  loading: false,
  loadingWidgets: {
    clippingWidget: false,
  },
  currentStep: '',
  projects: [],
  workspaces: [],
  workspace: '',
  userInfo: null,
  channelType: '',
  keywords: {},
  searchData: [],
  isSearchPerformed: false,
  numberOfPages: 0,
  numberOfPosts: 0,
  newProjectId: null,
  newWorkspaceId: null,
  searchPage: 1,
  dimensionAuthors: null,
  dimensionLanguages: null,
  dimensionCountries: null,
  dimensionSources: null,
  selectedFilters: {},
  countries: [],
  languages: [],
  sources: [],
  authors: [],
  additionalFilters: {},
  summary: {},
  volume: {},
  clippingFeedContent: [],
  topAuthors: [],
  topBrands: [],
  topCountries: [],
  topLanguages: [],
  topSharingSources: [],
  sourcesByLanguage: [],
  sourcesByCountry: [],
  overallTopSources: [],
  sentimentTopSources: {},
  sentimentTopCountries: {},
  sentimentTopLanguages: {},
  sentimentTopAuthors: {},
  sentimentForPeriod: [],
  contentVolumeTopSources: [],
  contentVolumeTopAuthors: [],
  contentVolumeTopCountries: [],
  sentimentTopKeywordsWidget: {},
  topKeywordsWidget: [],
  sentimentDiagram: [],
  sentimentNumberOfResult: [],
  authorsByCountry: [],
  authorsByLanguage: [],
  authorsBySentiment: [],
  overallTopAuthors: [],
  dimensions: [],
  templates: [],
  newWorkspace: {
    title: '',
    description: '',
    members: [],
    projects: [],
    department: null,
  },
  newProject: {
    title: '',
    note: '',
    keywords: [],
    additional_keywords: [],
    ignore_keywords: [],
    max_items: '',
    image: null,
    arabic_name: '',
    english_name: '',
    social: false,
    online: false,
    premium: false,
    creator: null,
    source: '',
    workspace: null,
    start_search_date: null,
    end_search_date: null,
  },
  isShowCalendarContents: false,
  inreractiveDataModal: {
    isShow: false,
  },
  availableWidgets: null,
  companyUsers: [],
  interactiveData: [],
  paginationData: {},

  //reports
  regularReports: [],
  reportWidgetsLists: new Map(),
  newReport: {
    step: 1,
    name: '',
    description: '',
    report_language: 'English',
    report_format: 'PDF',
    report_template: '',
    projects: [],
    widgetsTemplates: {},
  },
  // Account Analysis
  newAccountAnalysisWorkspace: {
    step: 1,
    title: '',
    description: '',
    department: null,
    members: [],
    account_analysis_workspace_projects: [],
    projects: [],
  },

  newAccountAnalysisProject: {
    title: '',
    profile_handle: '',
    start_search_date: null,
    end_search_date: null,
    min_followers: null,
    max_followers: null,
    language_filter: [],
    country_filter: [],
    sentiment_filter: [],
    source_filter: [],
    author_filter: [],
    language_dimensions: [],
    country_dimensions: [],
    sentiment_dimensions: [],
    source_dimensions: [],
    author_dimensions: [],
    creator: null,
    workspace: null,
    members: [],
  },

  // 24/7
  newTFSWorkspace: {
    step: 1,
    title: '',
    description: '',
    department: null,
    members: [],
    tfs_workspace_projects: [],
    projects: [],
  },

  newTFSProject: {
    step: 2,
    title: '',
    profile_handle: '',
    start_search_date: null,
    end_search_date: null,
    min_followers: null,
    max_followers: null,
    language_filter: [],
    country_filter: [],
    sentiment_filter: [],
    source_filter: [],
    author_filter: [],
    language_dimensions: [],
    country_dimensions: [],
    sentiment_dimensions: [],
    source_dimensions: [],
    author_dimensions: [],
    creator: null,
    workspace: null,
    members: [],
    project_type: '',
  },
}

const state = {...initialState}

export default state
