from . import summary_widget_image, top_10_authors_widget_image, volume_widget_image, top_10_sources_widget_image, top_10_countries_widget_image, top_10_languages_widget_image, sentiment_top_10_sources_widget_image, sentiment_top_10_authors_image, sentiment_top_10_countries_image, sentiment_top_10_languages_image, sentiment_for_period_widget_image

def prepare_widget_images(project_id):
  summary_widget_image.create_summary_widget_image(project_id)
  top_10_authors_widget_image.create_top_10_authors_wid_image(project_id)
  volume_widget_image.create_vol_widget_image(project_id)
  top_10_sources_widget_image.create_top_10_sources_wid_image(project_id)
  top_10_countries_widget_image.create_top_10_countries_wid_image(project_id)
  top_10_languages_widget_image.create_top_10_languages_wid_image(project_id)
  sentiment_top_10_sources_widget_image.create_sentiment_top_10_sources_wid_image(project_id)
  sentiment_top_10_authors_image.create_sentiment_top_10_authors_wid_image(project_id)
  sentiment_top_10_countries_image.create_sentiment_top_10_countries_wid_image(project_id)
  sentiment_top_10_languages_image.create_sentiment_top_10_languages_wid_image(project_id)
  sentiment_for_period_widget_image.create_sentiment_for_period_widget_image(project_id)
