# Generated by Django 4.0.6 on 2022-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_department_id_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', upload_to='static/user_image'),
            preserve_default=False,
        ),
    ]
