# Generated by Django 4.0.6 on 2022-09-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/department_logo'),
        ),
        migrations.AddField(
            model_name='department',
            name='max_online_feeds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='department',
            name='max_projects',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='department',
            name='max_social_feeds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='department',
            name='max_twitter_data',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='department',
            name='max_users',
            field=models.IntegerField(default=1),
        ),
    ]
