# Generated by Django 4.0.6 on 2023-01-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('regular_user', 'Regular User'), ('picker', 'Picker'), ('writer', 'Writer'), ('publisher', 'Publisher')], default='Regular User', max_length=30, null=True),
        ),
    ]
