# Generated by Django 4.0.6 on 2023-01-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='current_number_of_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='current_number_of_users',
            field=models.IntegerField(default=0),
        ),
    ]
