# Generated by Django 4.0.6 on 2023-04-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_department_current_number_of_social_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='current_number_of_account_analysis_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='max_projects_account_analysis',
            field=models.IntegerField(default=1),
        ),
    ]
