# Generated by Django 4.0.6 on 2023-08-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_department_current_number_of_account_analysis_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='platform_language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='English', max_length=10),
        ),
    ]
