# Generated by Django 4.0.6 on 2022-12-16 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_post_entry_author_gin_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('email_title', models.TextField(blank=True, max_length=500, null=True)),
                ('minute', models.CharField(default='*', max_length=2)),
                ('hour', models.CharField(default='*', max_length=2)),
                ('day_of_week', models.CharField(default='*', max_length=2)),
                ('day_of_month', models.CharField(default='*', max_length=2)),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('crontab_schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.crontabschedule')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.templates')),
                ('user', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
