# Generated by Django 4.0.6 on 2022-12-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('reports', '0003_rename_ending_date_regularreport_d_ending_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularreport',
            name='template',
        ),
        migrations.AddField(
            model_name='regularreport',
            name='d_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_d_template', to='reports.templates'),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='h_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_h_template', to='reports.templates'),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='m_day_of_month',
            field=models.CharField(default='*', max_length=4),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='m_day_of_week',
            field=models.CharField(default='*', max_length=4),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='m_ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='m_hour',
            field=models.CharField(default='*', max_length=4),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='m_minute',
            field=models.CharField(default='*', max_length=4),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='m_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_m_template', to='reports.templates'),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='monthly_crontab_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_m_crontab_sch', to='django_celery_beat.crontabschedule'),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='monthly_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='monthly_periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_m_periodic_task', to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='w_day_of_month',
            field=models.CharField(default='*', max_length=4),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='w_day_of_week',
            field=models.CharField(default='*', max_length=4),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='w_ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='w_hour',
            field=models.CharField(default='*', max_length=4),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='w_minute',
            field=models.CharField(default='*', max_length=4),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='w_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_w_template', to='reports.templates'),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='weekly_crontab_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_w_crontab_sch', to='django_celery_beat.crontabschedule'),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='weekly_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='weekly_periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_w_periodic_task', to='django_celery_beat.periodictask'),
        ),
    ]
