# Generated by Django 4.0.6 on 2023-02-21 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_regularreport_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
