# Generated by Django 4.0.6 on 2023-03-30 13:15

from django.db import migrations, models
import django.db.models.deletion

def populate_new_columns(apps, schema_editor):
    RegularReport = apps.get_model('reports', 'RegularReport')
    RegularReport.objects.filter(project=None).delete()
    for report in RegularReport.objects.all():
        report.module_type = 'Project'
        report.module_project_id = report.project_id
        report.department = report.project.creator.user_profile.department
        report.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_department_current_number_of_social_projects_and_more'),
        ('reports', '0005_regularreport_created_at_regularreport_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularreport',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='module_project_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularreport',
            name='module_type',
            field=models.CharField(choices=[('Project', 'Online'), ('ProjectSocial', 'Social')], default='Project', max_length=70),
            preserve_default=False,
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
