# Generated by Django 4.0.6 on 2023-04-05 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def populate_new_columns(apps, schema_editor):
        RegularReport = apps.get_model('reports', 'RegularReport')
        reports = RegularReport.objects.all()
        for rr in reports:
            rr.creator = rr.department.department_users.all()[0].user
            rr.save()

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0006_regularreport_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularreport',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_report_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=populate_new_columns,
            reverse_code=migrations.RunPython.noop
        ),
    ]
