# Generated by Django 4.0.6 on 2023-04-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_regularreport_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularreport',
            name='dashboard_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='demography_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='gender_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='influencers_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='photo_video_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='report_format',
            field=models.CharField(blank=True, default='pdf', max_length=3),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='report_language',
            field=models.CharField(default='English', max_length=10),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_report_templates', to='reports.templates'),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='sentiment_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='summary_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularreport',
            name='topic_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
