# Generated by Django 4.0.6 on 2023-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_regularreport_onl_authors_by_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=70)),
                ('module_project_id', models.IntegerField(blank=True, null=True)),
                ('onl_summary_widget', models.BooleanField(default=False)),
                ('onl_volume_widget', models.BooleanField(default=False)),
                ('onl_clipping_feed_content_widget', models.BooleanField(default=False)),
                ('onl_top_10_authors_by_volume_widget', models.BooleanField(default=False)),
                ('onl_top_10_brands_widget', models.BooleanField(default=False)),
                ('onl_top_10_countries_widget', models.BooleanField(default=False)),
                ('onl_top_10_languages_widget', models.BooleanField(default=False)),
                ('onl_content_volume_top_5_source_widget', models.BooleanField(default=False)),
                ('onl_sentiment_top_10_sources_widget', models.BooleanField(default=False)),
                ('onl_sentiment_top_10_countries_widget', models.BooleanField(default=False)),
                ('onl_sentiment_top_10_authors_widget', models.BooleanField(default=False)),
                ('onl_sentiment_top_10_languages_widget', models.BooleanField(default=False)),
                ('onl_sentiment_for_period_widget', models.BooleanField(default=False)),
                ('onl_content_volume_top_5_authors_widget', models.BooleanField(default=False)),
                ('onl_content_volume_top_5_countries_widget', models.BooleanField(default=False)),
                ('onl_top_keywords', models.BooleanField(default=False)),
                ('onl_sentiment_top_keywords', models.BooleanField(default=False)),
                ('onl_sentiment_number_of_results', models.BooleanField(default=False)),
                ('onl_sentiment_diagram', models.BooleanField(default=False)),
                ('onl_authors_by_country', models.BooleanField(default=False)),
                ('onl_top_sharing_sources', models.BooleanField(default=False)),
                ('onl_overall_top_sources', models.BooleanField(default=False)),
                ('onl_sources_by_country', models.BooleanField(default=False)),
                ('onl_sources_by_language', models.BooleanField(default=False)),
                ('onl_authors_by_language', models.BooleanField(default=False)),
                ('onl_authors_by_sentiment', models.BooleanField(default=False)),
                ('onl_overall_top_authors', models.BooleanField(default=False)),
                ('soc_summary', models.BooleanField(default=False)),
                ('soc_clipping_feed_content', models.BooleanField(default=False)),
                ('soc_top_locations', models.BooleanField(default=False)),
                ('soc_top_authors', models.BooleanField(default=False)),
                ('soc_top_languages', models.BooleanField(default=False)),
                ('soc_content_volume', models.BooleanField(default=False)),
                ('soc_content_volume_by_top_locations', models.BooleanField(default=False)),
                ('soc_content_volume_by_top_authors', models.BooleanField(default=False)),
                ('soc_content_volume_by_top_languages', models.BooleanField(default=False)),
                ('soc_sentiment', models.BooleanField(default=False)),
                ('soc_gender_volume', models.BooleanField(default=False)),
                ('soc_sentiment_number_of_results', models.BooleanField(default=False)),
                ('soc_sentiment_authors', models.BooleanField(default=False)),
                ('soc_sentiment_locations', models.BooleanField(default=False)),
                ('soc_sentiment_languages', models.BooleanField(default=False)),
                ('soc_sentiment_by_gender', models.BooleanField(default=False)),
                ('soc_top_keywords', models.BooleanField(default=False)),
                ('soc_sentiment_top_keywords', models.BooleanField(default=False)),
                ('soc_sentiment_diagram', models.BooleanField(default=False)),
                ('soc_top_sharing_sources', models.BooleanField(default=False)),
                ('soc_overall_top_authors', models.BooleanField(default=False)),
                ('soc_top_authors_by_gender', models.BooleanField(default=False)),
                ('soc_authors_by_language', models.BooleanField(default=False)),
                ('soc_authors_by_location', models.BooleanField(default=False)),
                ('soc_authors_by_sentiment', models.BooleanField(default=False)),
                ('soc_authors_by_gender', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='dashboard_is_active',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='demography_is_active',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='gender_is_active',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='influencers_is_active',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='module_project_id',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_authors_by_country',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_authors_by_language',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_authors_by_sentiment',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_clipping_feed_content_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_content_volume_top_5_authors_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_content_volume_top_5_countries_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_content_volume_top_5_source_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_overall_top_authors',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_overall_top_sources',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_sentiment_diagram',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_sentiment_for_period_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_sentiment_number_of_results',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_sentiment_top_10_authors_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_sentiment_top_10_countries_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_sentiment_top_10_languages_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_sentiment_top_10_sources_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_sentiment_top_keywords',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_sources_by_country',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_sources_by_language',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_summary_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_top_10_authors_by_volume_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_top_10_brands_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_top_10_countries_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_top_10_languages_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_top_keywords',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_top_sharing_sources',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='onl_volume_widget',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='photo_video_is_active',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='sentiment_is_active',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_authors_by_gender',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_authors_by_language',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_authors_by_location',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_authors_by_sentiment',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_clipping_feed_content',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_content_volume',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_content_volume_by_top_authors',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_content_volume_by_top_languages',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_content_volume_by_top_locations',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_gender_volume',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_overall_top_authors',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_sentiment',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_sentiment_authors',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_sentiment_by_gender',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_sentiment_diagram',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_sentiment_languages',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_sentiment_locations',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_sentiment_number_of_results',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_sentiment_top_keywords',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_summary',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_top_authors',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_top_authors_by_gender',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_top_keywords',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_top_languages',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_top_locations',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='soc_top_sharing_sources',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='summary_is_active',
        ),
        migrations.RemoveField(
            model_name='regularreport',
            name='topic_is_active',
        ),
        migrations.AddField(
            model_name='regularreport',
            name='items',
            field=models.ManyToManyField(null=True, to='reports.reportitem'),
        ),
    ]
