# Generated by Django 4.0.6 on 2023-04-28 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0010_reportitem_remove_regularreport_dashboard_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularreport',
            name='items',
            field=models.ManyToManyField(blank=True, to='reports.reportitem'),
        ),
        migrations.AlterField(
            model_name='regularreport',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
