# Generated by Django 4.0.6 on 2023-05-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_rename_onl_clipping_feed_content_widget_reportitem_onl_clipping_feed_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportitem',
            old_name='onl_content_volume_top_source',
            new_name='onl_content_volume_top_sources',
        ),
    ]
