# Generated by Django 4.0.6 on 2023-06-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_rename_onl_content_volume_top_source_reportitem_onl_content_volume_top_sources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportitem',
            old_name='onl_top_authors_by_volume',
            new_name='onl_top_authors',
        ),
    ]
