# Generated by Django 4.0.6 on 2023-06-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_rename_onl_top_authors_by_volume_reportitem_onl_top_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportitem',
            old_name='onl_top_brands',
            new_name='onl_top_sources',
        ),
    ]
