# Generated by Django 4.0.6 on 2023-07-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_rename_onl_top_brands_reportitem_onl_top_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='soc_gender_by_location',
            field=models.BooleanField(default=False),
        ),
    ]
