# Generated by Django 4.0.6 on 2023-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_reportitem_soc_gender_by_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='soc_keywords_by_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='soc_languages_by_location',
            field=models.BooleanField(default=False),
        ),
    ]
