# Generated by Django 4.0.6 on 2023-08-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_reportitem_soc_keywords_by_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='onl_keywords_by_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportitem',
            name='onl_languages_by_country',
            field=models.BooleanField(default=False),
        ),
    ]
