# Generated by Django 4.0.6 on 2023-02-10 05:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetBinderPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20, unique=True)),
                ('async_ops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('binders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('count_textlength', models.IntegerField(blank=True, null=True)),
                ('count_sentiment', models.IntegerField(blank=True, null=True)),
                ('count_retweets', models.IntegerField(blank=True, null=True)),
                ('count_totalretweets', models.IntegerField(blank=True, null=True)),
                ('count_favorites', models.IntegerField(blank=True, null=True)),
                ('count_hashtags', models.IntegerField(blank=True, null=True)),
                ('count_images', models.IntegerField(blank=True, null=True)),
                ('count_links', models.IntegerField(blank=True, null=True)),
                ('count_linksandimages', models.IntegerField(blank=True, null=True)),
                ('count_mentions', models.IntegerField(blank=True, null=True)),
                ('count_originals', models.IntegerField(blank=True, null=True)),
                ('count_clears', models.IntegerField(blank=True, null=True)),
                ('count_replies', models.IntegerField(blank=True, null=True)),
                ('count_publicationscore', models.IntegerField(blank=True, null=True)),
                ('count_uservalue', models.FloatField(blank=True, null=True)),
                ('count_tweetvalue', models.FloatField(blank=True, null=True)),
                ('createdat', models.IntegerField(blank=True, null=True)),
                ('favorites', models.IntegerField(blank=True, null=True)),
                ('hashtags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('inreplyto', models.CharField(blank=True, max_length=100, null=True)),
                ('inreplytoid', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('mentions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('locationString', models.CharField(blank=True, max_length=50, null=True)),
                ('retweets', models.IntegerField(blank=True, null=True)),
                ('sentiment_vote', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('updatedat', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('user_picture', models.CharField(blank=True, max_length=300, null=True)),
                ('user_followers', models.IntegerField(blank=True, null=True)),
                ('user_following', models.IntegerField(blank=True, null=True)),
                ('user_verified', models.BooleanField(default=False)),
                ('user_bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_counts_lists', models.IntegerField(blank=True, null=True)),
                ('user_statuses', models.IntegerField(blank=True, null=True)),
                ('user_location', models.CharField(blank=True, max_length=100, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('user_value', models.FloatField(blank=True, null=True)),
                ('videos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TweetBinderProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('limit', models.IntegerField(blank=True, default=10, null=True)),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
