# Generated by Django 4.0.6 on 2023-02-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_binder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetbinderproject',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweetbinderproject',
            name='search_type',
            field=models.CharField(blank=True, choices=[('basic search', 'Basic search'), ('historical search', 'Historical search'), ('live search', 'Live search')], default='Basic search', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tweetbinderproject',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
