# Generated by Django 4.0.6 on 2023-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_binder', '0003_basicsearchproject_historicalsearchproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.IntegerField(blank=True, default=10, null=True)),
                ('keyword', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
