# Generated by Django 4.0.6 on 2023-03-03 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_binder', '0005_tweetbinderpost_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetbinderpost',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
