# Generated by Django 4.0.6 on 2023-03-22 11:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_binder', '0007_tweetbinderpost_date_tweetbinderpost_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsearchproject',
            name='keyword_and',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Keywords AND'),
        ),
        migrations.AddField(
            model_name='basicsearchproject',
            name='keyword_nor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Keywords excluded'),
        ),
        migrations.AddField(
            model_name='basicsearchproject',
            name='keyword_or',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Keywords OR'),
        ),
        migrations.AddField(
            model_name='historicalsearchproject',
            name='keyword_and',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Keywords AND'),
        ),
        migrations.AddField(
            model_name='historicalsearchproject',
            name='keyword_nor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Keywords excluded'),
        ),
        migrations.AddField(
            model_name='historicalsearchproject',
            name='keyword_or',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Keywords OR'),
        ),
        migrations.AddField(
            model_name='livesearchproject',
            name='keyword_and',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Keywords AND'),
        ),
        migrations.AddField(
            model_name='livesearchproject',
            name='keyword_nor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Keywords excluded'),
        ),
        migrations.AddField(
            model_name='livesearchproject',
            name='keyword_or',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Keywords OR'),
        ),
    ]
