# Generated by Django 4.0.6 on 2023-04-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_binder', '0008_basicsearchproject_keyword_and_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetBinderUserTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_alias', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TweetBinderUserTrackerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id_start', models.CharField(blank=True, max_length=100, null=True)),
                ('tracker_id_end', models.CharField(blank=True, max_length=100, null=True)),
                ('mentions_start', models.CharField(blank=True, max_length=100, null=True)),
                ('mentions_end', models.CharField(blank=True, max_length=100, null=True)),
                ('tweets_start', models.CharField(blank=True, max_length=100, null=True)),
                ('tweets_end', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_start', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_end', models.CharField(blank=True, max_length=100, null=True)),
                ('originals_start', models.CharField(blank=True, max_length=100, null=True)),
                ('originals_end', models.CharField(blank=True, max_length=100, null=True)),
                ('retweet_statuses_start', models.CharField(blank=True, max_length=100, null=True)),
                ('retweet_statuses_end', models.CharField(blank=True, max_length=100, null=True)),
                ('retweets_start', models.CharField(blank=True, max_length=100, null=True)),
                ('retweets_end', models.CharField(blank=True, max_length=100, null=True)),
                ('favorites_start', models.CharField(blank=True, max_length=100, null=True)),
                ('favorites_end', models.CharField(blank=True, max_length=100, null=True)),
                ('followers_start', models.CharField(blank=True, max_length=100, null=True)),
                ('followers_end', models.CharField(blank=True, max_length=100, null=True)),
                ('following_start', models.CharField(blank=True, max_length=100, null=True)),
                ('following_end', models.CharField(blank=True, max_length=100, null=True)),
                ('lists_start', models.CharField(blank=True, max_length=100, null=True)),
                ('lists_end', models.CharField(blank=True, max_length=100, null=True)),
                ('followers_following_start', models.CharField(blank=True, max_length=100, null=True)),
                ('followers_following_end', models.CharField(blank=True, max_length=100, null=True)),
                ('user_value_start', models.CharField(blank=True, max_length=100, null=True)),
                ('user_value_end', models.CharField(blank=True, max_length=100, null=True)),
                ('engagement_value_start', models.CharField(blank=True, max_length=100, null=True)),
                ('engagement_value_end', models.CharField(blank=True, max_length=100, null=True)),
                ('global_score_start', models.CharField(blank=True, max_length=100, null=True)),
                ('global_score_end', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at_start', models.DateTimeField(auto_now_add=True)),
                ('created_at_end', models.DateTimeField(auto_now_add=True)),
                ('updated_at_start', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet_binder.tweetbinderusertracker')),
            ],
        ),
    ]
