# Generated by Django 4.0.6 on 2023-10-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_binder', '0013_tweetbinderpost_tweet_binde_date_42834a_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalSearchProject',
            new_name='EnterpriseSearchProject',
        ),
    ]
