# Generated by Django 4.0.6 on 2023-11-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_binder', '0014_rename_historicalsearchproject_enterprisesearchproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicsearchproject',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='enterprisesearchproject',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='livesearchproject',
            name='keyword',
        ),
    ]
