# Generated by Django 4.0.6 on 2023-12-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_binder', '0015_remove_basicsearchproject_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetbinderpost',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweetbinderpost',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
