# Generated by Django 4.0.6 on 2023-12-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_binder', '0017_tweetbinderpost_country'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweetbinderpost',
            index=models.Index(fields=['user_alias'], name='tweet_binde_user_al_afdee0_idx'),
        ),
        migrations.AddIndex(
            model_name='tweetbinderpost',
            index=models.Index(fields=['country'], name='tweet_binde_country_65bbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='tweetbinderpost',
            index=models.Index(fields=['language'], name='tweet_binde_languag_d967dc_idx'),
        ),
    ]
