export const action = {
  GET_WORKSPACES: 'GET_WORKSPACES',
  CREATE_WORKSPACE: 'CREATE_WORKSPACE',
  UPDATE_WORKSPACE: 'UPDATE_WORKSPACE',
  DELETE_WORKSPACE: 'DELETE_WORKSPACE',
  GET_PROJECTS: 'GET_PROJECTS',
  CREATE_PROJECT: 'CREATE_PROJECT',
  POST_SEARCH: 'POST_SEARCH',
  GET_CLIPPING_FEED_CONTENT_WIDGET: 'GET_CLIPPING_FEED_CONTENT_WIDGET',
  CREATE_CLIPPING_FEED_CONTENT_WIDGET: 'CREATE_CLIPPING_FEED_CONTENT_WIDGET',
  DELETE_CLIPPING_FEED_CONTENT: 'DELETE_CLIPPING_FEED_CONTENT',
}

export const mutator = {
  SET_LOADING: 'SET_LOADING',
  SET_WORKSPACES: 'SET_WORKSPACES',
  SET_NEW_WORKSPACE_ID: 'SET_NEW_WORKSPACE_ID',
  SET_NEW_PROJECT_ID: 'SET_NEW_PROJECT_ID',
  UPDATE_WORKSPACE: 'UPDATE_WORKSPACE',
  SET_PROJECTS: 'SET_PROJECTS',
}

export const get = {
  LOADING: 'LOADING',
  WORKSPACES: 'WORKSPACES',
  NEW_WORKSPACE_ID: 'NEW_WORKSPACE_ID',
  NEW_PROJECT_ID: 'NEW_PROJECT_ID',
}
