export const action = {
  GET_WORKSPACES: 'GET_WORKSPACES',
  CREATE_WORKSPACE: 'CREATE_WORKSPACE',
  UPDATE_WORKSPACE: 'UPDATE_WORKSPACE',
  DELETE_WORKSPACE: 'DELETE_WORKSPACE',
}

export const mutator = {
  SET_LOADING: 'SET_LOADING',
  SET_WORKSPACES: 'SET_WORKSPACES',
  SET_NEW_WORKSPACE_ID: 'SET_NEW_WORKSPACE_ID',
  SET_NEW_PROJECT_ID: 'SET_NEW_PROJECT_ID',
  UPDATE_WORKSPACE: 'UPDATE_WORKSPACE',
}

export const get = {
  LOADING: 'LOADING',
  WORKSPACES: 'WORKSPACES',
  NEW_WORKSPACE_ID: 'NEW_WORKSPACE_ID',
  NEW_PROJECT_ID: 'NEW_PROJECT_ID',
}
