# Generated by Django 4.0.6 on 2023-04-21 11:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_analysis', '0002_projectaccountanalysis_country_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountanalysiswidgetdescription',
            name='author_dimensions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='projectaccountanalysis',
            name='author_dimensions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='projectaccountanalysis',
            name='author_filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
    ]
