# Generated by Django 4.0.6 on 2023-04-28 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_analysis', '0006_accountanalysiswidgetslist_most_engaging_post_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaccountanalysis',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects_account_analysis', to=settings.AUTH_USER_MODEL),
        ),
    ]
