# Generated by Django 4.0.6 on 2023-05-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_analysis', '0007_alter_projectaccountanalysis_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaccountanalysis',
            name='members',
        ),
        migrations.AlterField(
            model_name='projectaccountanalysis',
            name='end_search_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectaccountanalysis',
            name='max_followers',
            field=models.IntegerField(blank=True, default=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='projectaccountanalysis',
            name='min_followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectaccountanalysis',
            name='start_search_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
