# Generated by Django 4.0.6 on 2023-05-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_analysis', '0008_remove_projectaccountanalysis_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountanalysiswidgetslist',
            name='most_engaging_media_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_analysis_most_engaging_media_types', to='account_analysis.accountanalysiswidgetdescription'),
        ),
        migrations.AddField(
            model_name='accountanalysiswidgetslist',
            name='most_frequent_media_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_analysis_most_frequent_media_types', to='account_analysis.accountanalysiswidgetdescription'),
        ),
        migrations.AddField(
            model_name='projectaccountanalysis',
            name='count_posts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='projectaccountanalysis',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
