# Generated by Django 4.0.6 on 2023-05-12 06:28

from django.db import migrations, models
import django.db.models.deletion

def populate_new_columns(apps, schema_editor):
    AccountAnalysisWidgetsList = apps.get_model('account_analysis', 'AccountAnalysisWidgetsList')
    AccountAnalysisWidgetDescription = apps.get_model('account_analysis', 'AccountAnalysisWidgetDescription')
    wl = AccountAnalysisWidgetsList.objects.all()
    for i in wl:
        wd = AccountAnalysisWidgetDescription.objects.create(title='Optimal number of hashtags', default_title='Optimal number of hashtags')
        wd.save()
        i.optimal_number_of_hashtags = wd
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('account_analysis', '0012_accountanalysiswidgetslist_top_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountanalysiswidgetslist',
            name='optimal_number_of_hashtags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimal_number_of_hashtags', to='account_analysis.accountanalysiswidgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
