# Generated by Django 4.0.6 on 2023-05-17 12:49

from django.db import migrations, models
import django.db.models.deletion

def populate_new_columns(apps, schema_editor):
    AccountAnalysisWidgetsList = apps.get_model('account_analysis', 'AccountAnalysisWidgetsList')
    AccountAnalysisWidgetDescription = apps.get_model('account_analysis', 'AccountAnalysisWidgetDescription')
    wl = AccountAnalysisWidgetsList.objects.all()
    for i in wl:
        wd = AccountAnalysisWidgetDescription.objects.create(title='Average engagements by day', default_title='Average engagements by day')
        wd.save()
        i.average_engagements_by_day = wd
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account_analysis', '0013_accountanalysiswidgetslist_optimal_number_of_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountanalysiswidgetslist',
            name='average_engagements_by_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='average_engagements_by_day', to='account_analysis.accountanalysiswidgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
