# Generated by Django 4.0.6 on 2023-05-26 08:06

from django.db import migrations, models
import django.db.models.deletion

def populate_new_columns(apps, schema_editor):
    AccountAnalysisWidgetsList = apps.get_model('account_analysis', 'AccountAnalysisWidgetsList')
    AccountAnalysisWidgetDescription = apps.get_model('account_analysis', 'AccountAnalysisWidgetDescription')
    wl = AccountAnalysisWidgetsList.objects.all()
    for i in wl:
        wd = AccountAnalysisWidgetDescription.objects.create(title='Top mentions by engagements', default_title='Top mentions by engagements')
        wd.save()
        i.top_mentions_by_engagements = wd
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('account_analysis', '0020_accountanalysiswidgetslist_mention_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountanalysiswidgetslist',
            name='top_mentions_by_engagements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_mentions_by_engagements', to='account_analysis.accountanalysiswidgetdescription'),
        ),
         migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
