# Generated by Django 4.0.6 on 2023-05-30 09:34

from django.db import migrations, models
import django.db.models.deletion

def populate_new_columns(apps, schema_editor):
    AccountAnalysisWidgetsList = apps.get_model('account_analysis', 'AccountAnalysisWidgetsList')
    AccountAnalysisWidgetDescription = apps.get_model('account_analysis', 'AccountAnalysisWidgetDescription')
    wl = AccountAnalysisWidgetsList.objects.all()
    for i in wl:
        wd = AccountAnalysisWidgetDescription.objects.create(title='Average engagements by day (mentions)', default_title='Average engagements by day (mentions)')
        wd.save()
        i.average_engagements_by_day_for_mentions = wd
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('account_analysis', '0023_accountanalysiswidgetslist_audience_mention_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountanalysiswidgetslist',
            name='average_engagements_by_day_for_mentions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='average_engagements_by_day_for_mentions', to='account_analysis.accountanalysiswidgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
