# Generated by Django 4.0.6 on 2022-11-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='privious_posts_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
