# Generated by Django 4.0.6 on 2022-10-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0018_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_widget', models.BooleanField(default=False)),
                ('volume_widget', models.BooleanField(default=False)),
                ('project', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='widget_list', to='project.project')),
            ],
        ),
    ]
