# Generated by Django 4.0.6 on 2022-10-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_post_project_pos_feedlin_7ba78f_idx_and_more'),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClippingFeedContentWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='project.post', verbose_name='Post')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project')),
            ],
        ),
    ]
