# Generated by Django 4.0.6 on 2022-10-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_clippingfeedcontentwidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetslist',
            name='clipping_feed_content_widget',
            field=models.BooleanField(default=False),
        ),
    ]
