# Generated by Django 4.0.6 on 2022-10-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_widgetslist_clipping_feed_content_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetslist',
            name='top_10_authors_by_volume_widget',
            field=models.BooleanField(default=False),
        ),
    ]
