# Generated by Django 4.0.6 on 2022-10-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_post_entry_title_gin_index'),
        ('widgets', '0004_widgetslist_top_10_authors_by_volume_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(default='Title', max_length=30)),
                ('description', models.TextField(default='Description')),
                ('aggregation_period', models.CharField(default='day', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetsList2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clipping_feed_content_widget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cl_fd_cont_widg_description', to='widgets.widgetdescription')),
                ('project', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.project')),
                ('summary_widget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sum_widg_description', to='widgets.widgetdescription')),
                ('top_10_authors_by_volume_widget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_10_auth_by_vol_widg_description', to='widgets.widgetdescription')),
                ('volume_widget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol_widg_description', to='widgets.widgetdescription')),
            ],
        ),
    ]
