# Generated by Django 4.0.6 on 2022-11-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0006_dimensions_projectdimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdescription',
            name='linked_dimensions',
            field=models.ManyToManyField(to='widgets.dimensions'),
        ),
    ]
