# Generated by Django 4.0.6 on 2022-11-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0007_widgetdescription_linked_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdescription',
            name='author_dim_pivot',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='widgetdescription',
            name='country_dim_pivot',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='widgetdescription',
            name='language_dim_pivot',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='widgetdescription',
            name='sentiment_dim_pivot',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='widgetdescription',
            name='source_dim_pivot',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
