# Generated by Django 4.0.6 on 2022-11-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0009_alter_widgetdescription_linked_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetslist2',
            name='clipping_widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clippint_widg_description', to='widgets.widgetdescription'),
        ),
    ]
