# Generated by Django 4.0.6 on 2022-12-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0011_alter_widgetslist2_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetslist2',
            name='clipping_widget',
        ),
    ]
