# Generated by Django 4.0.6 on 2022-12-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0017_alter_widgetdescription_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetslist2',
            name='sentiment_top_10_sources_widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_top_10_sources_widget', to='widgets.widgetdescription'),
        ),
    ]
