# Generated by Django 4.0.6 on 2022-12-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0018_widgetslist2_sentiment_top_10_sources_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetslist2',
            name='sentiment_top_10_countries_widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_top_10_countries_widget', to='widgets.widgetdescription'),
        ),
    ]
