# Generated by Django 4.0.6 on 2022-12-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0022_widgetslist2_content_volume_top_10_authors_widget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdescription',
            name='title_for_change',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
