# Generated by Django 4.0.6 on 2022-12-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0023_widgetdescription_title_for_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetdescription',
            name='title_for_change',
        ),
        migrations.AddField(
            model_name='widgetdescription',
            name='default_title',
            field=models.CharField(default='Default Title', max_length=50),
        ),
    ]
