# Generated by Django 4.0.6 on 2023-01-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0027_alter_widgetdescription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdescription',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
