# Generated by Django 4.0.6 on 2023-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0028_alter_widgetdescription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdescription',
            name='chart_type',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
