# Generated by Django 4.0.6 on 2023-02-20 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0029_widgetdescription_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdescription',
            name='author_dim_pivot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='widgetdescription',
            name='country_dim_pivot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='widgetdescription',
            name='language_dim_pivot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='widgetdescription',
            name='sentiment_dim_pivot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='widgetdescription',
            name='source_dim_pivot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=None, null=True, size=None),
        ),
    ]
