# Generated by Django 4.0.6 on 2023-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0031_alter_widgetdescription_author_dim_pivot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdescription',
            name='chart_type',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
