# Generated by Django 4.0.6 on 2023-03-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0033_widgetdescription_top_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetslist2',
            name='top_keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_keywords', to='widgets.widgetdescription'),
        ),
    ]
