# Generated by Django 4.0.6 on 2023-03-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0035_widgetslist2_sentiment_top_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetslist2',
            name='sentiment_diagram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_diagram', to='widgets.widgetdescription'),
        ),
        migrations.AddField(
            model_name='widgetslist2',
            name='sentiment_number_of_results',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_number_of_results', to='widgets.widgetdescription'),
        ),
    ]
