# Generated by Django 4.0.6 on 2023-04-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def populate_new_columns(apps, schema_editor):
            WidgetsList = apps.get_model('widgets', 'WidgetsList2')
            WidgetDescriptions = apps.get_model('widgets', 'WidgetDescription')
            wl = WidgetsList.objects.all()
            for i in wl:
                w1 = WidgetDescriptions.objects.create(title='Overall top sources', default_title='Overall top sources')
                w1.save()
                w2 = WidgetDescriptions.objects.create(title='Sources by country', default_title='Sources by country')
                w2.save()
                w3 = WidgetDescriptions.objects.create(title='Sources by language', default_title='Sources by language')
                w3.save()
                w4 = WidgetDescriptions.objects.create(title='Top sharing sources', default_title='Top sharing sources')
                w4.save()
                i.overall_top_sources = w1
                i.sources_by_country = w2
                i.sources_by_language = w3
                i.top_sharing_sources = w4
                i.save()

    dependencies = [
        ('widgets', '0037_widgetslist2_authors_by_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetslist2',
            name='overall_top_sources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overall_top_sources', to='widgets.widgetdescription'),
        ),
        migrations.AddField(
            model_name='widgetslist2',
            name='sources_by_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources_by_country', to='widgets.widgetdescription'),
        ),
        migrations.AddField(
            model_name='widgetslist2',
            name='sources_by_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources_by_language', to='widgets.widgetdescription'),
        ),
        migrations.AddField(
            model_name='widgetslist2',
            name='top_sharing_sources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_sharing_sources', to='widgets.widgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
