# Generated by Django 4.0.6 on 2023-04-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def populate_new_columns(apps, schema_editor):
        WidgetsList = apps.get_model('widgets', 'WidgetsList2')
        WidgetDescriptions = apps.get_model('widgets', 'WidgetDescription')
        wl = WidgetsList.objects.all()
        for i in wl:
            w1 = WidgetDescriptions.objects.create(title='Overall top authors', default_title='Overall top authors')
            w1.save()
            w2 = WidgetDescriptions.objects.create(title='Authors by sentiment', default_title='Authors by sentiment')
            w2.save()
            w3 = WidgetDescriptions.objects.create(title='Authors by language', default_title='Authors by language')
            w3.save()
            i.overall_top_authors = w1
            i.authors_by_sentiment = w2
            i.authors_by_language = w3
            i.save()

    dependencies = [
        ('widgets', '0038_widgetslist2_overall_top_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetslist2',
            name='authors_by_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors_by_language', to='widgets.widgetdescription'),
        ),
        migrations.AddField(
            model_name='widgetslist2',
            name='authors_by_sentiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors_by_sentiment', to='widgets.widgetdescription'),
        ),
        migrations.AddField(
            model_name='widgetslist2',
            name='overall_top_authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overall_top_authors', to='widgets.widgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
