# Generated by Django 4.0.6 on 2023-05-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0040_rename_clipping_feed_content_widget_widgetslist2_clipping_feed_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetslist2',
            name='authors_by_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_authors_by_country', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='authors_by_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_authors_by_language', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='authors_by_sentiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_authors_by_sentiment', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='clipping_feed_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_clipping_feed_content', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='content_volume_top_authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_content_volume_top_authors', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='content_volume_top_countries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_content_volume_top_countries', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='content_volume_top_sources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_content_volume_top_sources', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='overall_top_authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_overall_top_authors', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='overall_top_sources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_overall_top_sources', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='sentiment_diagram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_sentiment_diagram', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='sentiment_for_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_sentiment_for_period', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='sentiment_number_of_results',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_sentiment_number_of_results', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='sentiment_top_authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_sentiment_top_authors', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='sentiment_top_countries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_sentiment_top_countries', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='sentiment_top_keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_sentiment_top_keywords', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='sentiment_top_languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_sentiment_top_languages', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='sentiment_top_sources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_sentiment_top_sources', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='sources_by_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_sources_by_country', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='sources_by_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_sources_by_language', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_summary', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='top_authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_top_authors', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='top_brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_top_brands', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='top_countries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_top_countries', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='top_keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_top_keywords', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='top_languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_top_languages', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='top_sharing_sources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_top_sharing_sources', to='widgets.widgetdescription'),
        ),
        migrations.AlterField(
            model_name='widgetslist2',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_volume', to='widgets.widgetdescription'),
        ),
    ]
