# Generated by Django 4.0.6 on 2023-05-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def populate_new_columns(apps, schema_editor):
        WidgetsList = apps.get_model('widgets', 'WidgetsList2')
        WidgetDescriptions = apps.get_model('widgets', 'WidgetDescription')
        wl = WidgetsList.objects.all()
        for i in wl:
            w = WidgetDescriptions.objects.create(title='Top keywords by country', default_title='Top keywords by country')
            w.save()
            i.top_keywords_by_country = w
            i.save()

    dependencies = [
        ('widgets', '0041_alter_widgetslist2_authors_by_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetslist2',
            name='top_keywords_by_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onl_top_keywords_by_country', to='widgets.widgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
