# Generated by Django 4.0.6 on 2023-06-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0043_widgetslist2_languages_by_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgetslist2',
            old_name='top_brands',
            new_name='top_sources',
        ),
    ]
