# Generated by Django 4.0.6 on 2023-10-11 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_post_source_type_alter_changingonlinesentiment_post'),
        ('widgets', '0046_alter_clippingfeedcontentwidget_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clippingfeedcontentwidget',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='project.post', verbose_name='Post'),
        ),
    ]
