# Generated by Django 4.0.6 on 2023-11-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0047_alter_clippingfeedcontentwidget_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetdescription',
            name='linked_dimensions',
        ),
    ]
