# Generated by Django 4.0.6 on 2022-09-01 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('max_users', models.IntegerField()),
                ('max_projects', models.IntegerField()),
                ('max_online_feeds', models.IntegerField()),
                ('max_social_feeds', models.IntegerField()),
                ('max_twitter_data', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='social',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.company')),
                ('members', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='workspase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.workspace'),
        ),
    ]
