# Generated by Django 4.0.6 on 2022-09-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_company_project_online_project_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedlinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='Source')),
                ('page', models.CharField(blank=True, max_length=200, null=True, verbose_name='Page')),
                ('creator', models.IntegerField(default=1, verbose_name='Creator')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('lastupdate', models.DateTimeField(auto_now=True)),
                ('errornotes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Error Note')),
                ('nooffeeds', models.IntegerField(default=0)),
                ('circle', models.IntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country')),
                ('source1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Source1')),
                ('boze', models.CharField(blank=True, max_length=30, null=True, verbose_name='Boze')),
                ('myscript', models.CharField(blank=True, max_length=30, null=True, verbose_name='Script')),
                ('status_code', models.IntegerField(default=0)),
                ('linklanguage', models.CharField(blank=True, max_length=200, null=True, verbose_name='Language')),
                ('languagecode', models.CharField(blank=True, max_length=2, null=True, verbose_name='Language Code')),
                ('sourceurl', models.URLField(blank=True, null=True)),
                ('issourcefeed', models.BooleanField(default=False)),
            ],
        ),
    ]
