# Generated by Django 4.0.6 on 2022-09-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_members_alter_project_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='workspase',
            new_name='workspace',
        ),
    ]
