# Generated by Django 3.2.14 on 2022-09-15 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_workspase_project_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
