# Generated by Django 3.2.14 on 2022-09-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
