# Generated by Django 4.0.6 on 2022-09-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feed_language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='speech', to='project.speech'),
            preserve_default=False,
        ),
    ]
