# Generated by Django 4.0.6 on 2022-09-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_post_feed_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feedlink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedlink_feedsin', to='project.feedlinks', verbose_name='Feed Link'),
            preserve_default=False,
        ),
    ]
