# Generated by Django 4.0.6 on 2022-09-30 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_post_feedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='entry_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
