# Generated by Django 4.0.6 on 2022-10-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_post_entry_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=8, verbose_name='sentiment'),
        ),
    ]
