# Generated by Django 4.0.6 on 2022-10-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_post_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
