# Generated by Django 4.0.6 on 2022-10-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_workspace_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['entry_title'], name='project_pos_entry_t_5fa8ac_idx'),
        ),
    ]
