# Generated by Django 4.0.6 on 2022-10-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_project_end_search_date_project_start_search_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['entry_published'], name='project_pos_entry_p_11d5f0_idx'),
        ),
    ]
