# Generated by Django 4.0.6 on 2022-10-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_post_project_pos_entry_p_11d5f0_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['feedlink'], name='project_pos_feedlin_7ba78f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['entry_author'], name='project_pos_entry_a_cdfd57_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['feed_language'], name='project_pos_feed_la_0635c7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['sentiment'], name='project_pos_sentime_5f04fc_idx'),
        ),
    ]
