# Generated by Django 4.0.6 on 2022-10-27 14:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_post_project_pos_feedlin_7ba78f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['entry_title'], name='entry_title_gin_index', opclasses=['gin_trgm_ops']),
        ),
    ]
