# Generated by Django 4.0.6 on 2022-11-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_project_report_content_project_report_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author_filter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='country_filter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='language_filter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='source_filter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
