# Generated by Django 4.0.6 on 2022-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_project_author_filter_project_country_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sentiment_filter',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
