# Generated by Django 4.0.6 on 2022-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_project_sentiment_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author_filter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='country_filter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='language_filter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sentiment_filter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_filter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
