# Generated by Django 4.0.6 on 2022-12-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_tempfeedlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedlinks',
            name='alexaglobalrank',
            field=models.BigIntegerField(default=0),
        ),
    ]
