# Generated by Django 4.0.6 on 2022-12-05 14:20

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_feedlinks_alexaglobalrank'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['entry_author'], name='entry_author_gin_index', opclasses=['gin_trgm_ops']),
        ),
    ]
