# Generated by Django 4.0.6 on 2023-01-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_post_entry_author_gin_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlinks',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
