# Generated by Django 4.0.6 on 2023-01-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_role'),
        ('project', '0034_remove_workspace_company_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='accounts.department'),
        ),
    ]
