# Generated by Django 4.0.6 on 2023-02-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_project_author_dimensions_project_country_dimensions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFeedlinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=400, null=True, unique=True)),
                ('source1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Source1')),
                ('sourceurl', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
