# Generated by Django 4.0.6 on 2023-02-09 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_crawlerkeyword_alter_project_language_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfeedlinks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newfeedlinks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
