# Generated by Django 4.0.6 on 2023-02-17 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_newfeedlinks_created_at_newfeedlinks_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedlinks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedlinks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
