# Generated by Django 4.0.6 on 2023-03-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_crawleroption_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleroption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='crawleroption',
            name='tbm',
            field=models.CharField(choices=[('None', 'Regular search'), ('isch', 'Google Images API'), ('lcl', 'Google Local API'), ('vid', 'Google Videos API'), ('nws', 'Google News API'), ('shop', 'Google Shopping API')], default='nws', max_length=5),
        ),
    ]
