# Generated by Django 4.0.6 on 2023-03-24 10:26

import django.contrib.postgres.fields
from django.db import migrations
import ndarraydjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_crawleroption_is_active_alter_crawleroption_tbm'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=ndarraydjango.fields.NDArrayField(editable=True, shape=384), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
