# Generated by Django 4.0.6 on 2023-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_post_summary_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imp_sentiment',
            field=models.CharField(default='', max_length=10, verbose_name='imp_sentiment'),
            preserve_default=False,
        ),
    ]
