# Generated by Django 4.0.6 on 2023-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_post_imp_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.CharField(blank=True, default='Online', max_length=100, null=True),
        ),
    ]
