# Generated by Django 4.0.6 on 2023-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_project_query_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expert_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='query_filter',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
