# Generated by Django 4.0.6 on 2023-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_changingsentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='full_text',
            field=models.TextField(blank=True, null=True, verbose_name='full_text'),
        ),
    ]
