# Generated by Django 4.0.6 on 2023-08-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0002_talkwalkerpost_talkwalker post uniqueness constraint'),
        ('project', '0054_alter_project_query_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changingonlinesentiment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkwalker.talkwalkerpost'),
        ),
    ]
