# Generated by Django 4.0.6 on 2023-09-22 14:48

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_alter_changingonlinesentiment_post'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='speech',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('language'), name='gin_trgm_ops'), name='tlw_language_gin_index'),
        ),
    ]
