# Generated by Django 4.0.6 on 2023-10-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_speech_tlw_language_gin_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Category'),
        ),
    ]
