# Generated by Django 4.0.6 on 2023-10-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_search_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_search_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
