# Generated by Django 4.0.6 on 2023-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0007_talkwalkerfeedlink_tlw_country_gin_index_and_more'),
        ('project', '0058_alter_project_end_search_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tw_posts',
            field=models.ManyToManyField(to='talkwalker.talkwalkerpost'),
        ),
    ]
