# Generated by Django 4.0.6 on 2023-10-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_alter_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='posts',
            field=models.ManyToManyField(to='project.post'),
        ),
    ]
