# Generated by Django 4.0.6 on 2023-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0007_talkwalkerfeedlink_tlw_country_gin_index_and_more'),
        ('project', '0061_project_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, to='project.post'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tw_posts',
            field=models.ManyToManyField(blank=True, null=True, to='talkwalker.talkwalkerpost'),
        ),
    ]
