# Generated by Django 4.0.6 on 2023-10-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0008_alter_talkwalkerpost_category_and_more'),
        ('project', '0062_alter_project_posts_alter_project_tw_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='entry_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='posts',
            field=models.ManyToManyField(blank=True, to='project.post'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tw_posts',
            field=models.ManyToManyField(blank=True, to='talkwalker.talkwalkerpost'),
        ),
    ]
