# Generated by Django 4.0.6 on 2023-10-11 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0064_remove_post_entry_author_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_type',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='source_type'),
        ),
        migrations.AlterField(
            model_name='changingonlinesentiment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.post'),
        ),
    ]
