# Generated by Django 4.0.6 on 2023-10-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_remove_feedlinks_boze_remove_feedlinks_circle_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='project_pos_entry_t_5fa8ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='project_pos_entry_a_cdfd57_idx',
        ),
    ]
