# Generated by Django 4.0.6 on 2023-10-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_remove_post_project_pos_entry_t_5fa8ac_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='entry_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='entry_summary_detail_language',
        ),
        migrations.RemoveField(
            model_name='post',
            name='entry_tags_term',
        ),
    ]
