# Generated by Django 4.0.6 on 2023-10-17 12:22

import django.contrib.postgres.fields
from django.db import migrations, models
import ndarraydjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_remove_post_entry_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imp_sentiment',
            field=models.CharField(default='neutral', max_length=10, verbose_name='imp_sentiment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=ndarraydjango.fields.NDArrayField(editable=True, shape=384), blank=True, default=list, size=None),
        ),
    ]
