# Generated by Django 4.0.6 on 2023-10-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0069_alter_post_imp_sentiment_alter_post_summary_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tw_posts',
        ),
    ]
