# Generated by Django 4.0.6 on 2023-10-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_remove_project_tw_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, default='collecting_data', max_length=20),
        ),
    ]
