# Generated by Django 4.0.6 on 2023-11-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL('UPDATE project_project SET start_date=start_search_date')
    ]
