# Generated by Django 4.0.6 on 2023-11-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0072_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('collecting_data', 'Collecting'), ('active', 'Active'), ('inactive', 'Inactive')], default='collecting_data', max_length=20),
        ),
        migrations.RunSQL("UPDATE project_project SET status='active'", reverse_sql=migrations.RunSQL.noop)
    ]
