# Generated by Django 4.0.6 on 2023-11-16 07:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0074_alter_project_author_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
