# Generated by Django 4.0.6 on 2023-11-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_filters', '0002_remove_preset_group_group_presets_alter_preset_query'),
        ('project', '0075_project_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expert_presets',
            field=models.ManyToManyField(blank=True, to='expert_filters.preset'),
        ),
    ]
