# Generated by Django 4.0.6 on 2023-12-08 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0078_project_resume_offset'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ProjectPost',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.post')),
                    ],
                    options={
                        'db_table': 'project_project_posts',
                    },
                ),
                migrations.AlterField(
                    model_name='project',
                    name='posts',
                    field=models.ManyToManyField(blank=True, through='project.ProjectPost', to='project.post'),
                ),
                migrations.AddField(
                    model_name='projectpost',
                    name='project',
                    field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
                ),
            ]
        )
    ]
