# Generated by Django 4.0.6 on 2023-12-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0079_projectpost_alter_project_posts_projectpost_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
