# Generated by Django 4.0.6 on 2023-12-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0080_projectpost_exclude'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='entry_author_gin_index',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['entry_author'], name='project_pos_entry_a_cdfd57_idx'),
        ),
    ]
