# Generated by Django 4.0.6 on 2023-12-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0081_remove_post_entry_author_gin_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=200, null=True, verbose_name='country'),
        ),
    ]
