# Generated by Django 4.0.6 on 2023-07-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0053_changingonlinesentiment_delete_changingsentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkwalkerFeedlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country')),
                ('source1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Source1')),
                ('sourceurl', models.URLField(blank=True, null=True)),
                ('alexaglobalrank', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TalkwalkerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.TextField(verbose_name='entry_title')),
                ('entry_published', models.DateTimeField(blank=True, null=True)),
                ('entry_summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('entry_media_thumbnail_url', models.TextField(blank=True, null=True, verbose_name='entry_media_thumbnail_url')),
                ('entry_media_content_url', models.TextField(blank=True, null=True, verbose_name='entry_media_content_url')),
                ('feed_image_href', models.TextField(blank=True, null=True, verbose_name='feed_image_href')),
                ('feed_image_link', models.TextField(blank=True, null=True, verbose_name='feed_image_link')),
                ('entry_author', models.TextField(blank=True, null=True, verbose_name='authors')),
                ('entry_links_href', models.TextField(blank=True, null=True, verbose_name='entry_links_href')),
                ('sentiment', models.CharField(blank=True, default='neutral', max_length=8, null=True, verbose_name='sentiment')),
                ('category', models.TextField(blank=True, null=True, verbose_name='Category')),
                ('feed_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tw_speech', to='project.speech')),
                ('feedlink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedlink_feedsin', to='talkwalker.talkwalkerfeedlink')),
            ],
        ),
    ]
