# Generated by Django 4.0.6 on 2023-08-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='talkwalkerpost',
            constraint=models.UniqueConstraint(fields=('entry_title', 'feedlink_id'), name='talkwalker post uniqueness constraint'),
        ),
    ]
