# Generated by Django 4.0.6 on 2023-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0002_talkwalkerpost_talkwalker post uniqueness constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkwalkerpost',
            name='full_text',
            field=models.TextField(blank=True, null=True, verbose_name='full_text'),
        ),
    ]
