# Generated by Django 4.0.6 on 2023-09-11 13:58

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0003_talkwalkerpost_full_text'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='talkwalkerpost',
            index=models.Index(fields=['entry_published'], name='talkwalker__entry_p_478a42_idx'),
        ),
        migrations.AddIndex(
            model_name='talkwalkerpost',
            index=models.Index(fields=['feedlink'], name='talkwalker__feedlin_b01698_idx'),
        ),
        migrations.AddIndex(
            model_name='talkwalkerpost',
            index=models.Index(fields=['entry_author'], name='talkwalker__entry_a_03867f_idx'),
        ),
        migrations.AddIndex(
            model_name='talkwalkerpost',
            index=models.Index(fields=['feed_language'], name='talkwalker__feed_la_f3bbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='talkwalkerpost',
            index=models.Index(fields=['sentiment'], name='talkwalker__sentime_c23646_idx'),
        ),
        migrations.AddIndex(
            model_name='talkwalkerpost',
            index=django.contrib.postgres.indexes.GinIndex(fields=['entry_title'], name='tlw_entry_title_gin_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='talkwalkerpost',
            index=django.contrib.postgres.indexes.GinIndex(fields=['entry_summary'], name='twk_entry_summary_gin_index', opclasses=['gin_trgm_ops']),
        ),
    ]
