# Generated by Django 4.0.6 on 2023-09-20 11:05

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0004_talkwalkerpost_talkwalker__entry_p_478a42_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='talkwalkerpost',
            name='tlw_entry_title_gin_index',
        ),
        migrations.RemoveIndex(
            model_name='talkwalkerpost',
            name='twk_entry_summary_gin_index',
        ),
        migrations.AddIndex(
            model_name='talkwalkerpost',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('entry_title'), name='gin_trgm_ops'), name='tlw_entry_title_gin_index'),
        ),
        migrations.AddIndex(
            model_name='talkwalkerpost',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('entry_summary'), name='gin_trgm_ops'), name='tlw_entry_summary_gin_index'),
        ),
    ]
