# Generated by Django 4.0.6 on 2023-09-22 13:34

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0005_remove_talkwalkerpost_tlw_entry_title_gin_index_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='talkwalkerpost',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('entry_author'), name='gin_trgm_ops'), name='tlw_entry_author_gin_index'),
        ),
    ]
