# Generated by Django 4.0.6 on 2023-09-22 14:48

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('talkwalker', '0006_talkwalkerpost_tlw_entry_author_gin_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='talkwalkerfeedlink',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('country'), name='gin_trgm_ops'), name='tlw_country_gin_index'),
        ),
        migrations.AddIndex(
            model_name='talkwalkerfeedlink',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('source1'), name='gin_trgm_ops'), name='tlw_source1_gin_index'),
        ),
    ]
