# Generated by Django 4.0.6 on 2023-06-07 13:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonWidgetDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(default='Title', max_length=50)),
                ('default_title', models.CharField(default='Default Title', max_length=50)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('aggregation_period', models.CharField(default='day', max_length=10)),
                ('country_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None)),
                ('language_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None)),
                ('sentiment_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None)),
                ('author_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None)),
                ('chart_type', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('top_counts', models.IntegerField(default=5)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmpr_widgets', to='comparison.projectcomparison')),
            ],
        ),
    ]
