WIDGETS_MAP = {
    'wid': { 'type': 'Online', 'name': 'Summary Widget' },
    'wid2': { 'type': 'Online', 'name': 'Content Volume' },
    'wid3': { 'type': 'Online', 'name': 'Top 10 authors by volume' },
    'wid4': { 'type': 'Online', 'name': 'Top 10 brands by volume' },
    'wid5': { 'type': 'Online', 'name': 'Top 10 countries by volume' },
    'wid6': { 'type': 'Online', 'name': 'Top 10 languages' },
    'wid7': { 'type': 'Online', 'name': 'Content Volume by Top 5 sources' },
    'wid8': { 'type': 'Online', 'name': 'Sentiment top 10 sources widget' },
    'wid9': { 'type': 'Online', 'name': 'Sentiment top 10 countries widget' },
    'wid10': { 'type': 'Online', 'name': 'Sentiment toop 10 authors widget' },
    'wid11': { 'type': 'Online', 'name': 'Sentiment top 10 languages widget' },
    'wid12': { 'type': 'Online', 'name': 'Sentiment for period widget' },
    'wid13': { 'type': 'Online', 'name': 'Content Volume by Top 5 authors' },
    'wid14': { 'type': 'Online', 'name': 'Content Volume by Top 5 countries' },
    'wid15': { 'type': 'Online', 'name': 'Clipping feed content' },
    'wid16': { 'type': 'Online', 'name': 'Top keywords' },
    'wid17': { 'type': 'Online', 'name': 'Sentiment top keywords' },
    'wid18': { 'type': 'Online', 'name': 'Sentiment number of results' },
    'wid19': { 'type': 'Online', 'name': 'Sentiment diagram' },
    'wid20': { 'type': 'Online', 'name': 'Authors by country' },
    'wid21': { 'type': 'Online', 'name': 'Authors by sentiment' },
    'wid22': { 'type': 'Online', 'name': 'Authors by language' },
    'wid23': { 'type': 'Online', 'name': 'Overall top authors' },
    'wid24': { 'type': 'Online', 'name': 'Overall top sources' },
    'wid25': { 'type': 'Online', 'name': 'Sources by country' },
    'wid26': { 'type': 'Online', 'name': 'Sources by language' },
    'wid27': { 'type': 'Online', 'name': 'Top sharing sources' },
    'wid28': { 'type': 'Social', 'name': 'Summary' },
    'wid29': { 'type': 'Social', 'name': 'Content volume' },
    'wid30': { 'type': 'Social', 'name': 'Top 10 authors by volume' },
    'wid31': { 'type': 'Social', 'name': 'Top 10 brands by volume' },
    'wid32': { 'type': 'Social', 'name': 'Top 10 countries by volume' },
    'wid33': { 'type': 'Social', 'name': 'Top 10 languages' },
    'wid34': { 'type': 'Social', 'name': 'Content Volume by Top 5 sources' },
    'wid35': { 'type': 'Social', 'name': 'Sentiment top 10 sources widget' },
    'wid36': { 'type': 'Social', 'name': 'Sentiment top 10 countries widget' },
    'wid37': { 'type': 'Social', 'name': 'Sentiment top 10 authors widget' },
    'wid38': { 'type': 'Social', 'name': 'Sentiment top 10 languages widget' },
    'wid39': { 'type': 'Social', 'name': 'Sentiment for period widget' },
    'wid40': { 'type': 'Social', 'name': 'Content Volume by Top 5 authors' },
    'wid41': { 'type': 'Social', 'name': 'Content Volume by Top 5 countries' },
    'wid42': { 'type': 'Social', 'name': 'Clipping feed content' },
    'wid43': { 'type': 'Social', 'name': 'Top keywords' },
    'wid44': { 'type': 'Social', 'name': 'Sentiment top keywords' },
    'wid45': { 'type': 'Social', 'name': 'Sentiment number of results' },
    'wid46': { 'type': 'Social', 'name': 'Sentiment diagram' },
    'wid47': { 'type': 'Social', 'name': 'Authors by country' },
    'wid48': { 'type': 'Social', 'name': 'Authors by sentiment' },
    'wid49': { 'type': 'Social', 'name': 'Authors by language' },
    'wid50': { 'type': 'Social', 'name': 'Overall top authors' },
    'wid51': { 'type': 'Social', 'name': 'Overall top sources' },
    'wid52': { 'type': 'Social', 'name': 'Sources by country' },
    'wid53': { 'type': 'Social', 'name': 'Sources by language' },
    'wid54': { 'type': 'Social', 'name': 'Top sharing sources' },
  }
