WIDGETS_NAMES = {
    'summary': 'Summary',
    'content_volume': 'Content volume',
    'top_authors': 'Top authors',
    'top_sources': 'Top sources',
    'sentiment': 'Sentiment',
    'top_keywords': 'Top keywords',
    'top_languages': 'Top languages',
    'top_locations': 'Top locations',
    'top_countries': 'Top countries',

    'sentiment_number_of_results': 'Sentiment number of results',
    'top_keywords_by_sentiment': 'Top keywords by sentiment',
    'sentiment_by_locations': 'Sentiment by location',
    'sentiment_by_period': 'Sentiment by period',
    'sentiment_top_languages': 'Sentiment by languages',
    'sentiment_top_authors': 'Sentiment by authors',

    'top_keywords_by_location': 'Top keywords by location',
    'authors_by_location': 'Authors by location',
    'top_languages_by_location': 'Top languages by location',
    'authors_by_gender': 'Authors by gender',
    'top_gender_by_location': 'Top gender by location',

    'top_sharing_sources': 'Top sharing sources',
    'authors_by_sentiment': 'Authors by sentiment',
    'overall_top_authors': 'Overall top authors',
    'top_authors_by_gender': 'Top authors by gender',
    'authors_by_language': 'Authors by language',
}
