# Generated by Django 4.0.6 on 2023-03-09 11:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0002_alter_projectsocial_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialWidgetDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(default='Title', max_length=50)),
                ('default_title', models.CharField(default='Default Title', max_length=50)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('aggregation_period', models.CharField(default='day', max_length=10)),
                ('author_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None)),
                ('country_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None)),
                ('source_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None)),
                ('language_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None)),
                ('sentiment_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None)),
                ('chart_type', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projectsocial',
            name='author_filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='projectsocial',
            name='country_filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='projectsocial',
            name='language_filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='projectsocial',
            name='sentiment_filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='projectsocial',
            name='source_filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.CreateModel(
            name='SocialWidgetsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clipping_feed_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_clipping_feed_content', to='project_social.socialwidgetdescription')),
                ('content_volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_content_volume', to='project_social.socialwidgetdescription')),
                ('content_volume_by_top_authors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_content_volume_by_top_authors', to='project_social.socialwidgetdescription')),
                ('content_volume_by_top_countries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_content_volume_by_top_countries', to='project_social.socialwidgetdescription')),
                ('content_volume_by_top_languages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_content_volume_by_top_languages', to='project_social.socialwidgetdescription')),
                ('gender_volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_genter_volume', to='project_social.socialwidgetdescription')),
                ('project', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='social_widgets_list', to='project_social.projectsocial')),
                ('sentiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_sentiment', to='project_social.socialwidgetdescription')),
                ('sentiment_authors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_sentiment_authors', to='project_social.socialwidgetdescription')),
                ('sentiment_by_gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_sentiment_by_gender', to='project_social.socialwidgetdescription')),
                ('sentiment_countries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_sentiment_countries', to='project_social.socialwidgetdescription')),
                ('sentiment_languages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_sentiment_languages', to='project_social.socialwidgetdescription')),
                ('sentiment_number_of_results', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_sentiment_number_of_results', to='project_social.socialwidgetdescription')),
                ('summary_widget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_summary_widget', to='project_social.socialwidgetdescription')),
                ('top_authors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_top_authors', to='project_social.socialwidgetdescription')),
                ('top_countries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_top_countries', to='project_social.socialwidgetdescription')),
                ('top_languages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_top_languages', to='project_social.socialwidgetdescription')),
            ],
        ),
    ]
