# Generated by Django 4.0.6 on 2023-03-10 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0003_socialwidgetdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialwidgetslist',
            name='content_volume_by_top_countries',
        ),
        migrations.RemoveField(
            model_name='socialwidgetslist',
            name='sentiment_countries',
        ),
        migrations.RemoveField(
            model_name='socialwidgetslist',
            name='top_countries',
        ),
        migrations.AddField(
            model_name='socialwidgetslist',
            name='content_volume_by_top_locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_content_volume_by_top_locations', to='project_social.socialwidgetdescription'),
        ),
        migrations.AddField(
            model_name='socialwidgetslist',
            name='sentiment_locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_sentiment_locations', to='project_social.socialwidgetdescription'),
        ),
        migrations.AddField(
            model_name='socialwidgetslist',
            name='top_locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_top_locations', to='project_social.socialwidgetdescription'),
        ),
    ]
