# Generated by Django 4.0.6 on 2023-03-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0005_remove_socialwidgetslist_summary_widget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialwidgetslist',
            name='top_keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_top_keywords', to='project_social.socialwidgetdescription'),
        ),
    ]
