# Generated by Django 4.0.6 on 2023-03-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_binder', '0006_tweetbinderpost_creation_date'),
        ('project_social', '0006_socialwidgetslist_top_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialClippingWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='tweet_binder.tweetbinderpost')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_social.projectsocial')),
            ],
        ),
        migrations.AddConstraint(
            model_name='socialclippingwidget',
            constraint=models.UniqueConstraint(fields=('project_id', 'post_id'), name='social clipping widget uniqueness constraint'),
        ),
    ]
