# Generated by Django 4.0.6 on 2023-03-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0007_socialclippingwidget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialwidgetslist',
            name='sentiment_diagram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_sentiment_diagram', to='project_social.socialwidgetdescription'),
        ),
        migrations.AddField(
            model_name='socialwidgetslist',
            name='sentiment_top_keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_sentiment_top_keywords', to='project_social.socialwidgetdescription'),
        ),
    ]
