# Generated by Django 4.0.6 on 2023-03-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def populate_new_columns(apps, schema_editor):
        SocialWidgetsList = apps.get_model('project_social', 'SocialWidgetsList')
        SocialWidgetDescriptions = apps.get_model('project_social', 'SocialWidgetDescription')
        wl = SocialWidgetsList.objects.all()
        for i in wl:
            wd21 = SocialWidgetDescriptions.objects.create(title='Overall top authors', default_title='Overall top authors')
            wd21.save()
            i.overall_top_authors = wd21
            i.save()

    dependencies = [
        ('project_social', '0009_socialwidgetslist_top_sharing_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialwidgetslist',
            name='overall_top_authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_overall_top_authors', to='project_social.socialwidgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
