# Generated by Django 4.0.6 on 2023-04-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def populate_new_columns(apps, schema_editor):
        SocialWidgetsList = apps.get_model('project_social', 'SocialWidgetsList')
        SocialWidgetDescriptions = apps.get_model('project_social', 'SocialWidgetDescription')
        wl = SocialWidgetsList.objects.all()
        for i in wl:
            w = SocialWidgetDescriptions.objects.create(title='Authors by language', default_title='Authors by language')
            w.save()
            i.authors_by_language = w
            i.save()

    dependencies = [
        ('project_social', '0011_socialwidgetslist_top_authors_by_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialwidgetslist',
            name='authors_by_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_authors_by_language', to='project_social.socialwidgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
