# Generated by Django 4.0.6 on 2023-04-04 12:50

from django.db import migrations, models
import django.db.models.deletion

def populate_new_columns(apps, schema_editor):
    SocialWidgetsList = apps.get_model('project_social', 'SocialWidgetsList')
    SocialWidgetDescriptions = apps.get_model('project_social', 'SocialWidgetDescription')
    wl = SocialWidgetsList.objects.all()
    for i in wl:
        w = SocialWidgetDescriptions.objects.create(title='Authors by location', default_title='Authors by location')
        w.save()
        i.authors_by_location = w
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0012_socialwidgetslist_authors_by_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialwidgetslist',
            name='authors_by_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_authors_by_location', to='project_social.socialwidgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
