# Generated by Django 4.0.6 on 2023-04-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_regularreport_creator'),
        ('project_social', '0016_projectsocial_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsocial',
            name='report_format',
            field=models.CharField(blank=True, default='pdf', max_length=3),
        ),
        migrations.AddField(
            model_name='projectsocial',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_social_templates', to='reports.templates'),
        ),
    ]
