# Generated by Django 4.0.6 on 2023-04-28 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_social', '0017_projectsocial_report_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsocial',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects_social', to=settings.AUTH_USER_MODEL),
        ),
    ]
