# Generated by Django 4.0.6 on 2023-05-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0019_rename_content_volume_by_top_authors_socialwidgetslist_content_volume_top_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialwidgetslist',
            name='content_volume_top_authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_content_volume_top_authors', to='project_social.socialwidgetdescription'),
        ),
        migrations.AlterField(
            model_name='socialwidgetslist',
            name='content_volume_top_languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_content_volume_top_languages', to='project_social.socialwidgetdescription'),
        ),
        migrations.AlterField(
            model_name='socialwidgetslist',
            name='content_volume_top_locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_content_volume_top_locations', to='project_social.socialwidgetdescription'),
        ),
    ]
