# Generated by Django 4.0.6 on 2023-05-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0020_alter_socialwidgetslist_content_volume_top_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsocial',
            name='expert_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectsocial',
            name='query_filter',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
