# Generated by Django 4.0.6 on 2023-06-14 08:24

from django.db import migrations, models
import django.db.models.deletion

def populate_new_columns(apps, schema_editor):
    SocialWidgetsList = apps.get_model('project_social', 'SocialWidgetsList')
    SocialWidgetDescription = apps.get_model('project_social', 'SocialWidgetDescription')
    wl = SocialWidgetsList.objects.all()
    for i in wl:
        wd = SocialWidgetDescription.objects.create(title='Top keywords by country', default_title='Top keywords by country')
        wd.save()
        i.keywords_by_country = wd
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0022_changingtweetbindersentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialwidgetslist',
            name='keywords_by_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords_by_country', to='project_social.socialwidgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
