# Generated by Django 4.0.6 on 2023-06-14 14:44

from django.db import migrations, models
import django.db.models.deletion

def populate_new_columns(apps, schema_editor):
    SocialWidgetsList = apps.get_model('project_social', 'SocialWidgetsList')
    SocialWidgetDescription = apps.get_model('project_social', 'SocialWidgetDescription')
    wl = SocialWidgetsList.objects.all()
    for i in wl:
        wd27 = SocialWidgetDescription.objects.create(title='Top keywords by location', default_title='Top keywords by location')
        wd27.save()
        wd28 = SocialWidgetDescription.objects.create(title='Top languages by location', default_title='Top languages by location')
        wd28.save()
        i.keywords_by_location = wd27
        i.languages_by_location = wd28
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0023_socialwidgetslist_keywords_by_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialwidgetslist',
            name='keywords_by_country',
        ),
        migrations.AddField(
            model_name='socialwidgetslist',
            name='keywords_by_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords_by_location', to='project_social.socialwidgetdescription'),
        ),
        migrations.AddField(
            model_name='socialwidgetslist',
            name='languages_by_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_by_location', to='project_social.socialwidgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
