# Generated by Django 4.0.6 on 2023-06-20 12:09

from django.db import migrations, models
import django.db.models.deletion

def populate_new_columns(apps, schema_editor):
    SocialWidgetsList = apps.get_model('project_social', 'SocialWidgetsList')
    SocialWidgetDescription = apps.get_model('project_social', 'SocialWidgetDescription')
    wl = SocialWidgetsList.objects.all()
    for i in wl:
        wd = SocialWidgetDescription.objects.create(title='Top gender by location', default_title='Top gender by location')
        wd.save()
        i.gender_by_location = wd
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0024_remove_socialwidgetslist_keywords_by_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialwidgetslist',
            name='gender_by_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_by_location', to='project_social.socialwidgetdescription'),
        ),
        migrations.RunPython(code=populate_new_columns, reverse_code=migrations.RunPython.noop),
    ]
