# Generated by Django 4.0.6 on 2023-11-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_filters', '0002_remove_preset_group_group_presets_alter_preset_query'),
        ('project_social', '0026_alter_projectsocial_query_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsocial',
            name='expert_presets',
            field=models.ManyToManyField(blank=True, to='expert_filters.preset'),
        ),
    ]
