# Generated by Django 4.0.6 on 2023-12-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_social', '0027_projectsocial_expert_presets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changingtweetbindersentiment',
            old_name='tweet_post',
            new_name='post',
        ),
    ]
